include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o


ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo")
obj-y   +=  nt35590_hd720_dsi_cmd_auo.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_wvga")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_wvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_fwvga")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_fwvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_qhd")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_qhd.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35512_wvga_dsi_vdo_yushun")
obj-y   +=  nt35512_wvga_dsi_vdo_yushun.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35512_wvga_dsi_vdo_yushun2")
obj-y   +=  nt35512_wvga_dsi_vdo_yushun2.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"ili9806e_wvga_dsi_vdo_boe")
obj-y   +=  ili9806e_wvga_dsi_vdo_boe.o
endif
